export const LEAD_DATA_LOADED = "LEAD_DATA_LOADED";

export const INVITE_DATA_LOADED = "INVITE_DATA_LOADED";

export const CUSTOMER_DATA_LOADED = "CUSTOMER_DATA_LOADED";
export const ATTORNEYS_LOADED = "ATTORNEYS_LOADED";
export const ELIGIBLE_ATTORNEYS_LOADED = "ELIGIBLE_ATTORNEYS_LOADED";
export const ASSIGNED_ATTORNEYS_LOADED = "ASSIGNED_ATTORNEYS_LOADED";

export const AFFILIATE_DATA_LOADED = "AFFILIATE_DATA_LOADED";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

//leads
export const GET_ALL_LEADS_LOADED = "GET_ALL_LEADS_LOADED";
export const GET_ALL_LEADS_FAILED_TO_LOAD = "GET_ALL_LEADS_FAILED_TO_LOAD";
export const UPDATE_ALL_LEADS_LOADED = "UPDATE_ALL_LEADS_LOADED";
export const UPDATE_ALL_LEADS_FAILED_TO_LOAD = "UPDATE_ALL_LEADS_FAILED_TO_LOAD";
export const GET_LEAD_DETAILS_LOADE = "GET_LEAD_DETAILS_LOADE";
export const GET_LEAD_DETAILS_FAILED_TO_LOAD = "GET_LEAD_DETAILS_FAILED_TO_LOAD";
export const GET_ALL_MOBILE_LEADS_LOADED = "GET_ALL_MOBILE_LEADS_LOADED";
export const GET_ALL_MOBILE_LEADS_FAILED_TO_LOAD = "GET_ALL_MOBILE_LEADS_FAILED_TO_LOAD";
export const SET_LEAD_TYPE = "SET_LEAD_TYPE";
export const ASSIGN_LEAD_IN_LEAD_DETAILS = "ASSIGN_LEAD_IN_LEAD_DETAILS";
export const FAILED_TO_ASSIGN_LEAD_IN_LEAD_DETAILS = "FAILED_TO_ASSIGN_LEAD_IN_LEAD_DETAILS";
export const LEAD_ANALYTICS_DATA = "LEAD_ANALYTICS_DATA";
export const USER_SEL_COLS_LEAD = "USER_SEL_COLS_LEAD";
export const LEADS_LOADING = "LEADS_LOADING";

//leads mark action
export const MARK_AS_TEST = "MARK_AS_TEST";
export const MARK_AS_LIVE = "MARK_AS_LIVE";
export const MARK_AS_DUPLICATE = "MARK_AS_DUPLICATE";
export const UNMARK_AS_DUPLICATE = "UNMARK_AS_DUPLICATE";
export const MARK_AS_STARRED = "MARK_AS_STARRED";
export const UNMARK_AS_STARRED = "UNMARK_AS_STARRED";
export const MARK_AS_FAKE = "MARK_AS_FAKE";
export const UNMARK_AS_FAKE = "UNMARK_AS_FAKE";
export const MARK_AS_LOW_QUALITY = "MARK_AS_LOW_QUALITY";
export const UNMARK_AS_LOW_QUALITY = "UNMARK_AS_LOW_QUALITY";
export const MARK_AS_WRONG_CASE_TYPE = "MARK_AS_WRONG_CASE_TYPE";
export const UNMARK_AS_WRONG_CASE_TYPE = "UNMARK_AS_WRONG_CASE_TYPE";
export const MARK_AS_WRONG_LOCATION = "MARK_AS_WRONG_LOCATION";
export const UNMARK_AS_WRONG_LOCATION = "UNMARK_AS_WRONG_LOCATION";

//leads filter
export const SET_FILTER = "SET_FILTER";
export const FAILED_TO_SET_FILTER = "FAILED_TO_SET_FILTER";

//attorneys in leads
export const ALL_ATTORNEYS_LOADED = "ALL_ATTORNEYS_LOADED";
export const ALL_ATTORNEYS_FAILED_TO_LOAD = "ALL_ATTORNEYS_FAILED_TO_LOAD";

//customers
export const ALL_CUSTOMERS_LOADED = "ALL_CUSTOMERS_LOADED";
export const ALL_CUSTOMERS_FAILED_TO_LOAD = "ALL_CUSTOMERS_FAILED_TO_LOAD";
export const GET_ALL_MOBILE_CUSTOMERS = "GET_ALL_MOBILE_CUSTOMERS";
export const GET_ALL_MOBILE_CUSTOMERS_FAILED_TO_LOAD = "GET_ALL_MOBILE_CUSTOMERS_FAILED_TO_LOAD";
export const CUSTOMER_DETAILS_LOADED = "CUSTOMER_DETAILS_LOADED";
export const ALL_CUSTOMER_DETAILS_FAILED_TO_LOAD = "ALL_CUSTOMER_DETAILS_FAILED_TO_LOAD";
export const CUSTOMERS_PURCHSED_LEADS_LOADED = "CUSTOMERS_PURCHSED_LEADS_LOADED";
export const CUSTOMERS_PURCHSED_LEADS_FAILED_TO_LOAD = "CUSTOMERS_PURCHSED_LEADS_FAILED_TO_LOAD";
export const CUSTOMERS_ELIGIBLE_LEADS_LOADED = "CUSTOMERS_ELIGIBLE_LEADS_LOADED";
export const CUSTOMERS_ELIGIBLE_LEADS_FAILED_TO_LOAD = "CUSTOMERS_ELIGIBLE_LEADS_FAILED_TO_LOAD";
export const CUSTOMERS_REPORTED_LEADS_LOADED = "CUSTOMERS_REPORTED_LEADS_LOADED";
export const CUSTOMERS_REPORTED_LEADS_FAILED_TO_LOAD = "CUSTOMERS_REPORTED_LEADS_FAILED_TO_LOAD";
export const CUSTOMERS_WEBSITE_ABOUT_LOADED = "CUSTOMERS_WEBSITE_ABOUT_LOADED";
export const CUSTOMERS_SPECIALIZATIONS_LOADED = "CUSTOMERS_SPECIALIZATIONS_LOADED";
export const CUSTOMERS_TESTIMONIALS_LOADED = "CUSTOMERS_TESTIMONIALS_LOADED";
export const CUSTOMERS_SETTLEMENTS_LOADED = "CUSTOMERS_SETTLEMENTS_LOADED";
export const LEAD_LIST_TYPE_LOADED = "LEAD_LIST_TYPE_LOADED";
export const BILLING_CYCLE_LOADED = "BILLING_CYCLE_LOADED";
export const NOTIFICATION_TO_LEADS_LOADED = "NOTIFICATION_TO_LEADS_LOADED";
export const NOTIFICAITON_TO_LAWFIRMS_LOADED = "NOTIFICAITON_TO_LAWFIRMS_LOADED";
export const PARTNER_LOADED = "PARTNER_LOADED";
export const FIRM_INFORMATION_LOADED = "FIRM_INFORMATION_LOADED";
export const ACCOUNT_INFORMATION_LOADED = "ACCOUNT_INFORMATION_LOADED";
export const ALL_CUSTOMERS_LOADING = "ALL_CUSTOMERS_LOADING";

//invite
export const ALL_INVITES_LOADED = "ALL_INVITES_LOADED";
export const ALL_INVITES_FAILED_TO_LOAD = "ALL_INVITES_FAILED_TO_LOAD";
export const INVITE_DETAILS_LOADED = "INVITE_DETAILS_LOADED";
export const INVITE_DETAILS_FAILED_TO_LOAD = "INVITE_DETAILS_FAILED_TO_LOAD";
export const GET_ATTORNEY_PROSPECTS = "GET_ATTORNEY_PROSPECTS";
export const ATTORNEY_PROSPECTS_FAILED_TO_LOAD = "ATTORNEY_PROSPECTS_FAILED_TO_LOAD";
export const SET_CREATE_INVITE_TOGGLE = "SET_CREATE_INVITE_TOGGLE";
export const UPDATE_ALL_INVITE_LOADED = "UPDATE_ALL_INVITE_LOADED";
export const UPDATE_ALL_INVITE_FAILED_TO_LOAD = "UPDATE_ALL_INVITE_FAILED_TO_LOAD";
export const GET_INVITE_DETAILS_LOADE = "GET_INVITE_DETAILS_LOADE";
export const GET_INVITE_DETAILS_FAILED_TO_LOAD = "GET_INVITE_DETAILS_FAILED_TO_LOAD";

// invite filter
export const FILTER_INVITE_NAME = "FILTER_NAME";
export const FILTER_INVITE_FIRM_NAME = "FILTER_FIRM_NAME";
export const FILTER_INVITE_EMAIL = "FILTER_EMAIL";
export const FILTER_INVITE_MOB = "FILTER_MOB";

//config
export const SET_CONFIG_USER_TYPE = "SET_CONFIG_USER_TYPE";
export const FAILED_TO_SET_CONFIG_USER_TYPE = "FAILED_TO_SET_CONFIG_USER_TYPE";
export const SET_CONFIG_TEST_MODE = "SET_CONFIG_TEST_MODE";
export const FAILED_TO_SET_CONFIG_TEST_MODE = " FAILED_TO_SET_CONFIG_TEST_MODE";


//affiliates
export const GET_AFFILIATE_LEAD_DATA = "GET_AFFILIATE_LEAD_DATA";
export const FAILED_TO_GET_AFFILIATE_LEAD_DATA = "FAILED_TO_GET_AFFILIATE_LEAD_DATA";
export const TEMP_AFFILIATE_DATA = "TEMP_AFFILIATE_DATA";

// affiliates filter
export const FILTER_AFFILIATE_NAME = "FILTER_AFFILIATE_NAME";
export const FILTER_AFFILIATE_LOCATION = "FILTER_AFFILIATE_LOCATION";
export const FILTER_AFFILIATE_CASETYPE = "FILTER_AFFILIATE_CASETYPE";
export const FILTER_AFFILIATE_TYPE = "FILTER_AFFILIATE_TYPE";

//website builder 
export const WEBSITE_DATA_LOADED = "WEBSITE_DATA_LOADED";
export const WEBSITE_TABLE_DATA_LOADED = "WEBSITE_TABLE_DATA_LOADED";
export const WEBSITE_TABLE_DATA_FAILED_TO_LOAD = "WEBSITE_TABLE_DATA_FAILED_TO_LOAD";
export const WEBSITE_DETAIL_DATA_LOADED = "WEBSITE_DETAIL_DATA_LOADED";
export const WEBSITE_DETAIL_DATA_FAILED_TO_LOAD = "WEBSITE_DETAIL_DATA_FAILED_TO_LOAD";
export const WEBSITE_DATA_LOADING = "WEBSITE_DATA_LOADING";

// website filter
export const FILTER_WEB_FIRM_NAME = "FILTER_WEB_FIRM_NAME";
export const FILTER_WEB_EMAIL = "FILTER_WEB_EMAIL";
export const FILTER_WEB_MOB = "FILTER_WEB_MOB";

//map
export const SEARCHED_BOUNDS_LOADED = "SEARCHED_BOUNDS_LOADED";
export const SEARCHED_BOUNDS_LOADING = "SEARCHED_BOUNDS_LOADING";